import streamlit as st
import tensorflow as tf
import numpy as np
from PIL import Image

# ---------------- PAGE CONFIG ----------------
st.set_page_config(
    page_title="Brain Tumor Detection",
    page_icon="🧠",
    layout="centered"
)

# ---------------- CUSTOM CSS ----------------
st.markdown("""
    <style>
        .title {
            text-align: center;
            color: #2C3E50;
            font-size: 40px;
            font-weight: bold;
        }
        .subtitle {
            text-align: center;
            color: #566573;
            font-size: 18px;
        }
        .result {
            font-size: 24px;
            font-weight: bold;
            text-align: center;
        }
    </style>
""", unsafe_allow_html=True)

# ---------------- TITLE ----------------
st.markdown('<div class="title">🧠 Brain Tumor Detection</div>', unsafe_allow_html=True)
st.markdown('<div class="subtitle">Upload a Brain MRI image to detect tumor</div>', unsafe_allow_html=True)
st.markdown("---")

# ---------------- LOAD MODEL ----------------
@st.cache_resource
def load_model():
    model = tf.keras.models.load_model("cn_mini_Pj/brain_mri_model.keras")


    return model

model = load_model()

# ---------------- IMAGE PREPROCESS ----------------
def preprocess_image(image):
    image = image.resize((224, 224))
    image = np.array(image) / 255.0
    image = np.expand_dims(image, axis=0)
    return image

# ---------------- FILE UPLOADER ----------------
uploaded_file = st.file_uploader(
    "📤 Upload Brain MRI Image",
    type=["jpg", "png", "jpeg"]
)

# ---------------- MAIN LOGIC ----------------
if uploaded_file is not None:
    image = Image.open(uploaded_file).convert("RGB")

    #st.image(image, caption="Uploaded MRI Image", use_column_width=True)
    st.image(image, caption="Uploaded MRI Image", use_container_width=True)



    if st.button("🔍 Analyze Image"):
        with st.spinner("Analyzing MRI Image..."):
            processed_image = preprocess_image(image)
            prediction = model.predict(processed_image)[0][0]

            confidence = prediction * 100

            if prediction >= 0.5:
                result = "🟥 Tumor Detected"
            else:
                result = "🟩 No Tumor Detected"

        st.markdown("---")
        st.markdown(f'<div class="result">{result}</div>', unsafe_allow_html=True)

        st.progress(int(confidence if confidence <= 100 else 100))

        st.write(f"### 📊 Confidence Score: **{confidence:.2f}%**")

        st.info(
            "⚠️ This result is generated by a deep learning model and should not be considered a medical diagnosis."
        )

else:
    st.warning("Please upload a Brain MRI image to proceed.")
